### ISSUE TITLE
when rust rewrite

### ISSUE THREAD

**Issue by partisani** [SethBling/cbscript#1]

**Comment by Sainan** [comment]
Learn a better language like C++

**Comment by krizej** [comment]
cbscript rewrite when

**Comment by aMyTimed** [comment]
rewrite in css

**Comment by Perthys** [comment]
TRUE

**Comment by MicroPanda123** [comment]
cpscript rewrite when

**Comment by SenkJu** [comment]
> Learn a better language like C++

Like PHP?

**Comment by gooncreeper** [comment]
x86 assembly rewrite when?

**Comment by nojasm** [comment]
CB++?

**Comment by partisani** [comment]
LOL

**Comment by datkat21** [comment]
just leave it closed <img src="https://cdn.discordapp.com/emojis/1082702315515031673.webp?size=48&quality=lossless" height=24>

**Comment by partisani** [comment]
nah

**Comment by LuisNordlSlav** [comment]
Odin lang rewrite when

**Comment by RustoMCSpit** [comment]
needs to be re-written in holy c, this is tomfoolery

**Comment by partisani** [comment]
6502 assembly better

**Comment by thennothinghappened** [comment]
this is the bootstrap compiler for the cbscript cbscript compiler :p

**Comment by Crinfarr** [comment]
if it can't self compile why even bother

**Comment by KatPurpy** [comment]
i suggest nocode
https://github.com/kelseyhightower/nocode

**Comment by SylvKT** [comment]
I'm being serious; this needs a rewrite in Java.

**Comment by Popaulol** [comment]
> I'm being serious; this needs a rewrite in Java.

Why though?
In my opinion the only languages that a rewrite of this would actually make sense in are:
- Modern Python
- Rust (only if people start writing codebases so large that the Python implementation gets unbearably slow)

**Comment by thennothinghappened** [comment]
Why not have this as a reference implementation of this transpiler, and once a spec is settled in writing others can make more optimised, modern versions? I don't think "rewrite this in another language please" is really a reasonable request here, but it makes more sense to instead shift to discussing standard spec, so that _others_ can then rewrite it in a more "suitable" language, and more capably for large projects _once they exist_.

**Comment by erikLundstedt** [comment]
Rewrite it in lua

/only kinda joking, especially as the language itself (cbscript) looks (from the video) quite lua-like
`end`

**Comment by aMyTimed** [comment]
> @aMyTimed: rewrite in css

after careful reconsideration i believe rewriting in microcode for your PC would be better and more efficient and even faster than rust

**Comment by RustoMCSpit** [comment]
re-write in latin please

**Comment by SethBling** [comment]
When Mojang adds native-binary plugins.

**Comment by IoIxD** [comment]
> When Mojang adds native-binary plugins.

I assume they meant the compiler itself?

**Comment by 7n7o** [comment]
> TRUE

Why Hello Perth........

**Comment by partisani** [comment]
Thank god this thread ended a long while ago

**Comment by Crinfarr** [comment]
do not poke the bear

**Comment by Perthys** [comment]
so its happening?>

**Comment by sylv256** [comment]
it's canon

**Comment by RustoMCSpit** [comment]
> Thank god this thread ended a long while ago

i concur
