### ISSUE TITLE
Include a license file

### ISSUE THREAD

**Issue by antznin** [SethBling/cbscript#13]
Since this project is free software/open source, it would really benefit from including a license file. Choice of license is of course left to the owner.

Please see https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license:

> without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work

**Comment by DivergentClouds** [comment]
duplicate of #3

**Comment by RustoMCSpit** [comment]
close this

**Comment by SethBling** [comment]
Duplicate of #3 .

**Comment by antznin** [comment]
Sorry about this, I missed the duplicate.
